Kirill refactor
IlyaZh/Maiman-MCBS pull request #36
Opened 2023-07-03 08:38 UTC by Ace966

2023-10-25 19:04 UTC, IlyaZh commented on multibench/model/device/devicewidget.cpp
> +      for (auto code : binaryWidget->Subscribe()) {
Старайся использовать const если значение не планируется изменять, то есть по умолчанию все конст.

2023-10-25 19:04 UTC, IlyaZh commented on multibench/widgets/binarywidget.cpp
> +  return QVector<quint16>(m_cmd.get()->code());
А зачем вектор? И разве это не получится вектор длиной code()?

2023-10-25 19:04 UTC, IlyaZh commented on multibench/widgets/controlwidget.cpp
> +void ControlWidget::getData(QSharedPointer<CommandConverter> data) {
по логике похоже на сетер, а не гетер

2023-10-25 19:04 UTC, IlyaZh commented on multibench/widgets/readparameterwidget.cpp
> +  m_labelValue->setText("    ");  // резервируем место под 5 символов, чтоб
ох, помню этот дикий запад))

2023-10-25 19:04 UTC, IlyaZh commented on multibench/gui/guiinterface.h
> +using commandData = std::variant<int, double, QString>;
А зачем оно? оно не используется? Или в структуре вместо 3х полей должно было быть? Это же для шины структура?

2023-10-25 19:04 UTC, IlyaZh commented on multibench/gui/guimediator.cpp
> +CommandConverter::CommandConverter(const CommandSettings& conf, quint16 value)
Давай лучше в отдельный файл, чтобы не смешивать. Сделай папочку utils или converters и клади туда. Если конечно их будет несколько - конвертеров или утилит. Иначе просто файл с именем = именем класса

2023-10-25 19:04 UTC, IlyaZh commented on multibench/gui/guimediator.cpp
> +QString CommandConverter::unit() const {
Кажется снова у нас куча ответственностей. Конвертер должен конвертировать. А тут он еще и значение передает. Вроде обсуждали что конвертер отдавать в виджет, куда класть значение через конструктор. а виджет уже распаковывает что там есть. Или даже в виджете поселить указатель на конвертер, где методы статистические конвертируют аля String convertToString(int value);

2023-10-25 19:04 UTC, IlyaZh commented on multibench/model/events/network.h
> +  SingleWriteRequest(quint8 address, quint16 reg, quint16 value)
можно не писать конструктор. И заполнять сразу структуру SingleWriteRequest{0x100, 0x34, 0x35} или в 20ом стандарте SingleWriteRequest{.address=3, .reg=4, .value = 5}

2023-10-25 19:04 UTC, IlyaZh commented on multibench/model/events/network.h
> +struct Answer {
вот как тут)

2023-10-25 19:04 UTC, IlyaZh commented on multibench/multibench.pro
> +QMAKE_CXXFLAGS += -std=c++17 -Wunused-parameter -Werror
не сработало? (

2023-10-25 19:04 UTC, IlyaZh commented on multibench/network/networkmodel.cpp
> +    auto data =
надо проверять есть ли там нужный обхект в variant.

```
if(!std::holds_alternative<model::events::network::SingleWriteRequest>(event.data_)) {
  // jopa
}
```

2023-10-25 19:04 UTC, IlyaZh commented on multibench/network/networkmodel.cpp
> +void NetworkModel::NewEvent(const model::Event& event) {
какая-то бесполезная штука?

2023-10-26 09:28 UTC, Ace966 commented on multibench/network/networkmodel.cpp
> +void NetworkModel::NewEvent(const model::Event& event) {
да, я вроде оставил ее для реализации интрефейса(т.к. без него ругался на отсутствие методов родителя)

2023-10-26 14:47 UTC, IlyaZh commented on multibench/network/networkmodel.cpp
> +void NetworkModel::NewEvent(const model::Event& event) {
временно? Потом то она будет полезную работу делать?

2023-11-13 20:09 UTC, Ace966 commented on multibench/device/device.cpp
> +                        QSharedPointer<CommandConverter>::create(cmdBuilder));
да, это исходный тип тут создается

2023-11-13 20:16 UTC, Ace966 commented on multibench/model/device/devicewidget.cpp
> +    auto code = std::get<model::events::network::Answer>(event.data_).reg_;
Тут можно сделать const auto& w = std::holds_alternative<>();

Чтобы не писать holds много раз и работать далее с w

2023-11-14 19:07 UTC, IlyaZh requested changes

2023-11-14 19:07 UTC, IlyaZh commented on multibench/main.cpp
> +  mediator.Subscribe(model::EventType::kDeviceStateUpdated, &gui);
два раза `kDeviceStateUpdated ` это баг или фича?
Если для совместимости со старой версией ок, но должно в итоге остаться по одному. Полет данных от сети к виджетам - это одно событие. Полет обратно - другое

2023-11-14 19:07 UTC, IlyaZh commented on multibench/model/device/devicewidget.cpp
> +    auto code = std::get<model::events::network::Answer>(event.data_).reg_;
дважды и более раз одинаковый get.

Заменяй на ссылку и используй ее как алиас
```
const auto a = std::get<>();

a.method();
a.var;
```

2023-11-14 19:07 UTC, IlyaZh commented on multibench/modelguimediator.h
> +  ConverterFactory* m_converters;
Это наследник от QObject? Если нет, то не используй сырые указатели

2023-11-14 19:07 UTC, IlyaZh commented on multibench/widgets/binarywidget.h
> +  void getData(quint16 code, quint16 data) override;
Странно что get метод а выглядит как сеттер) Давай че-нить сделаем

2023-11-14 19:07 UTC, IlyaZh commented on multibench/widgets/controlwidget.h
> +  void userEnteredData();
а в чем разница? между userEnteredValue и userEnteredData

2023-12-26 10:56 UTC, closed without merging