Test branch
IlyaZh/Maiman-MCBS pull request #38
Opened 2023-11-27 13:26 UTC by Ace966

2023-12-09 16:05 UTC, IlyaZh requested changes

2023-12-09 16:05 UTC, IlyaZh commented on multibench/group/groupcommandfactory.cpp
> +    QSet<quint8>& addresses, events::network::CommandType& command) {
По умолчанию ставь везде где можно const. Особенно если значение не должно изменяться

2023-12-09 16:05 UTC, IlyaZh commented on multibench/group/groupcommandfactory.h
> +using namespace model;
лучше не использовать такую штуку особенно в h файле - иначе ты ее экспортируешь. Внутри функции можно, если много объектов под таким неймспейсом. Если пара, проще напистаь явно model::event

2023-12-09 16:05 UTC, IlyaZh commented on multibench/model/event.h
> +                           network::SingleWriteRequest, network::FrontRequest>;
А что делает фронт риквест?
По идее есть рид и райт риквест 0- как раз чтобы либо считаьь значение , либо записать его в драйвер

2023-12-09 16:05 UTC, IlyaZh commented on multibench/widgets/groupwidget.cpp
> +GroupWidget::GroupWidget(QWidget *parent)
Для улучшения имен объектов можно выделять в неймспейсы - по структуре папок. Тогда тут будет widgets::Group

2023-12-24 09:14 UTC, IlyaZh requested changes

2023-12-24 09:14 UTC, IlyaZh commented on multibench/group/groupcommandfactory.cpp
> +const model::Event GroupCommandFactory::createGroupCommand(
Формально const можно не писать, ибо структуры все равно возвращаются копии

2023-12-24 09:14 UTC, IlyaZh commented on multibench/group/groupcommandfactory.cpp
> +    QSet<quint8>& addresses, model::events::network::CommandType& command) {
А вот тут нужен конст, если ты не собираешься менять значения аргументов в методе, тем более передаешь по ссылке

2023-12-24 09:14 UTC, IlyaZh commented on multibench/gui/guimediator.cpp
> +  GroupManager* manager = m_factory.createGroupManagerWidget(addrs);
чтоб не запариваться с типом можно писать просто `auto manager = `

2023-12-24 09:14 UTC, IlyaZh commented on multibench/gui/guimediator.cpp
> +void GuiMediator::createGroupWidgetFor(QSet<quint8> addresses) {
копировать сет каждый раз? Думаю нужно `const QSet<>&`

2023-12-24 09:14 UTC, IlyaZh commented on multibench/gui/guimediator.cpp
> +  QPointer<GroupWidget> group(m_factory.createGroupWidget());
тут QPointer, а выше сырой указатель. Старайся придерживаться одного стиля везде

2023-12-24 09:14 UTC, IlyaZh commented on multibench/gui/guimediator.cpp
> +          [this, addresses](model::Event event) {
Жирненькая лямбда, может ее в метод отдельный унести?

И model::Event снова копируется

2023-12-24 09:14 UTC, IlyaZh commented on multibench/gui/guimediator.cpp
> +void GuiMediator::deleteGroupWidgetFor(QSet<quint8> addresses) {
Аналогично просмотри плз аргументы методов, чтоб везде не писать)

2023-12-24 09:14 UTC, IlyaZh commented on multibench/mainwindow.cpp
> +  if (!m_workWidgets.contains(widget)) return;
ееее, ранний выход

2023-12-24 09:14 UTC, IlyaZh commented on multibench/mainwindow.cpp
> +  if (!m_groupWidgets.contains(group)) {
уууу, не ранний выход))))

2023-12-24 09:14 UTC, IlyaZh commented on multibench/model/device/devicewidget.cpp
> +const QMap<quint16, Button>& DeviceWidget::getButtonsDesc() const {
А мы разве не хотели унести это все из виджета? Типа в класс описания который из конфига береться?

2023-12-24 09:14 UTC, IlyaZh commented on multibench/model/guifactory.cpp
> +    const QSet<quint8> addresses) {
&

2023-12-24 09:14 UTC, IlyaZh commented on multibench/widgets/groupwidget.cpp
> +  //  if (member == this) return;
а эту почему закоментил?

2023-12-24 09:14 UTC, IlyaZh commented on multibench/widgets/groupwidget.cpp
> +  auto command = model::events::network::CommandType::cStartDevices;
`с` лишняя в сStartDevices

2023-12-25 11:02 UTC, Ace966 commented on multibench/model/device/devicewidget.cpp
> +const QMap<quint16, Button>& DeviceWidget::getButtonsDesc() const {
что-то я не помню такого, эти куски я забыл убрать(это остатки от общего интерфейса с группой)

2023-12-25 11:03 UTC, Ace966 commented on multibench/model/event.h
> +                           network::SingleWriteRequest, network::FrontRequest>;
я его добавлял для группового ивента общего запуска/стопа, наверно название выбрал неудачно

2023-12-26 06:16 UTC, IlyaZh requested changes

2023-12-26 06:16 UTC, IlyaZh commented on multibench/gui/guimediator.cpp
> +void GuiMediator::deleteGroupWidgetFor(const QSet<quint8> addresses) {
Ссылку забыл)

2023-12-26 06:16 UTC, IlyaZh commented on multibench/gui/guimediator.cpp
> +    if (group->getAddresses() == addresses) {
лучше ранний выход - если не равны, то continue

2023-12-26 06:16 UTC, IlyaZh commented on multibench/gui/guimediator.h
> +  void createGroupWidgetFor(const QSet<quint8> addresses);
&

2023-12-26 06:16 UTC, IlyaZh commented on multibench/model/device/devicewidget.h
> +  ~DeviceWidget() override;
красавчег)

2023-12-26 06:16 UTC, IlyaZh commented on multibench/model/devicefactory.cpp
> +    QString alias = "";
в принципе пустую строку можно не инициализировать. Или в дефолт - QString alias{};

2023-12-26 06:16 UTC, IlyaZh commented on multibench/model/event.h
> +                           network::SingleWriteRequest, network::FrontRequest>;
Да, лучше не использовать типа фронт риквест. Фронт чисто внутри ПО сущеситвует. А точнее только в нашем тг чате. Лучше что-то более приближенноек реальному миру и физическому смыслу

2023-12-26 10:56 UTC, merged